version: '3.9'

services:

  auth-service:
    build: ./backend/services/auth_service
    ports:
    - "8001:8000"

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

